let a=20;
let b=10;
console.log('No1:',a);
console.log('No2:',b);
console.log('----------- 1 -----------');
console.log("ADDITION:",a+b);
console.log('----------- 2 -----------');
console.log("SUBTRAION:",a-b);
console.log('----------- 3 -----------');
console.log("MULTIPLICATION:",a*b);
console.log('----------- 4 -----------');
console.log("DIVISION:",a/b);
console.log('----------- 5 -----------');
console.log("MODULE:",a%b);
console.log('----------- 6 -----------');
console.log("Grater-Than:",a>b);
console.log('----------- 7 -----------');
console.log("Less-Than:",a<b);
console.log('----------- 8 -----------');
console.log("Equal To:",a==b);
console.log('----------- 9 -----------');
console.log("Grater-Than:",a>=b);
console.log('----------- 10 -----------');
console.log("Less-Than:",a<=b);
console.log('----------- 11 -----------');
console.log("NOT Equal To:",a!=b);
console.log('----------- 12 -----------');
console.log("Addition Assignment:",a+=3);
console.log('----------- 13 -----------');
console.log("Subtraction Assignment:",a-=3);
console.log('----------- 14 -----------');
console.log("Multiplication Assignment:",a*=3);
console.log('----------- 15 -----------');
console.log("Division Assignment:",a/=3);
console.log('----------- 16 -----------');
console.log("Modulo Assignment:",a%=3);
console.log('----------- 17 -----------');
console.log("3 Equal to:",a===b);
console.log('----------- 18 -----------');
console.log("Square:",a**2);
console.log('----------- 19 -----------');
console.log("Logical AND:",a&&b);
console.log('----------- 20 -----------');
console.log("Logical OR:",a||b);
console.log('----------- 21 -----------');
console.log("Logical NOT Equal to:",a!=b);

